- name: Call webhook on push or PR
  run: |
    curl -X POST https://YOUR_NGROK_URL/webhook \
    -H "Content-Type: application/json" \
    -d '{
      "event": "${{ github.event_name }}",
      "author": "${{ github.actor }}",
      "from_branch": "${{ github.head_ref }}",
      "to_branch": "${{ github.base_ref }}",
      "timestamp": "${{ github.event.head_commit.timestamp }}"
    }'
